import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { resolveEntryOrder, resolveEntryOrderFor, applyEntryOrderChoice, readEntryOrderConfig, upsertEnvLine, type EntryOrderConfig } from './mcp.mjs';
import { orderEntries, buildVoucherXml, type VoucherEntry } from './voucher.mjs';

const DR: VoucherEntry = { ledger: 'Rent Expense', drCr: 'dr', amount: 5000 };
const CR: VoucherEntry = { ledger: 'HDFC Bank',    drCr: 'cr', amount: 5000 };

// --- the setting ------------------------------------------------------------------------------
// "Unset" is a distinct state from "set to the default". It is what makes the server ask instead of
// silently deciding how every voucher in someone's books will read.

test('an unset value is reported as unconfigured, not as the default', () => {
  const r = resolveEntryOrder(undefined);
  assert.equal(r.configured, false);
  assert.equal(r.order, 'credit-first');   // provisional, used only for dry runs
  assert.equal(resolveEntryOrder('').configured, false);
  assert.equal(resolveEntryOrder('   ').configured, false);
});

test('a typo is treated as unset rather than acted on', () => {
  // Silently falling back would post every voucher in an order nobody chose.
  assert.equal(resolveEntryOrder('creditfirst').configured, false);
  assert.equal(resolveEntryOrder('credit first').configured, false);
  assert.equal(resolveEntryOrder('dr-first').configured, false);
});

test('both real values are accepted, case and padding insensitive', () => {
  assert.deepEqual(resolveEntryOrder('credit-first'), { order: 'credit-first', configured: true });
  assert.deepEqual(resolveEntryOrder('debit-first'),  { order: 'debit-first',  configured: true });
  assert.deepEqual(resolveEntryOrder('  DEBIT-FIRST '), { order: 'debit-first', configured: true });
});

// --- the ordering itself ----------------------------------------------------------------------

test('credit-first puts credits ahead of debits, and debit-first reverses it', () => {
  assert.deepEqual(orderEntries([DR, CR], 'credit-first').map(e => e.drCr), ['cr', 'dr']);
  assert.deepEqual(orderEntries([DR, CR], 'debit-first').map(e => e.drCr),  ['dr', 'cr']);
});

test('order within a side is PRESERVED, which a naive sort would destroy', () => {
  // A GST sales invoice has several credit lines whose relative order is meaningful to whoever
  // reads the voucher. Partitioning must be stable.
  const entries: VoucherEntry[] = [
    { ledger: 'Debtors',     drCr: 'dr', amount: 11800 },
    { ledger: 'Sales',       drCr: 'cr', amount: 10000 },
    { ledger: 'CGST',        drCr: 'cr', amount: 900 },
    { ledger: 'SGST',        drCr: 'cr', amount: 900 },
  ];
  assert.deepEqual(
    orderEntries(entries, 'credit-first').map(e => e.ledger),
    ['Sales', 'CGST', 'SGST', 'Debtors']
  );
  assert.deepEqual(
    orderEntries(entries, 'debit-first').map(e => e.ledger),
    ['Debtors', 'Sales', 'CGST', 'SGST']
  );
});

test('reordering never changes the posting — only the sequence', () => {
  // The guarantee that makes this safe to flip. Tally reads Dr/Cr from ISDEEMEDPOSITIVE and the
  // sign of AMOUNT, never from position, so both orders must emit the identical set of lines.
  const cf = buildVoucherXml({ date: '2026-04-01', voucherType: 'Payment', entries: [DR, CR] }, undefined, 'credit-first');
  const df = buildVoucherXml({ date: '2026-04-01', voucherType: 'Payment', entries: [DR, CR] }, undefined, 'debit-first');

  const lines = (xml: string) => (xml.match(/<ALLLEDGERENTRIES\.LIST>.*?<\/ALLLEDGERENTRIES\.LIST>/g) ?? []);
  assert.equal(lines(cf).length, 2);
  assert.deepEqual([...lines(cf)].sort(), [...lines(df)].sort(), 'same lines, different sequence');
  assert.notDeepEqual(lines(cf), lines(df), 'sequence actually differs');

  // And the sign convention is untouched by either.
  assert.match(cf, /<LEDGERNAME>HDFC Bank<\/LEDGERNAME><ISDEEMEDPOSITIVE>No<\/ISDEEMEDPOSITIVE><AMOUNT>5000</);
  assert.match(cf, /<LEDGERNAME>Rent Expense<\/LEDGERNAME><ISDEEMEDPOSITIVE>Yes<\/ISDEEMEDPOSITIVE><AMOUNT>-5000</);
});

// --- persisting it ------------------------------------------------------------------------------
// .env is installer-generated AND hand-edited. Rewriting it from a parsed object would discard the
// comments that explain every other setting, so the writer touches one line and nothing else.

test('an existing key is replaced in place, leaving every other line alone', () => {
  const before = [
    '# Generated by the first-run wizard',
    'TALLY_PORT=9000',
    'ENTRY_ORDER=debit-first',
    '# trailing comment',
    'READONLY_MODE=false'
  ].join('\n');
  const after = upsertEnvLine(before, 'ENTRY_ORDER', 'credit-first');
  assert.equal(after.split('\n')[2], 'ENTRY_ORDER=credit-first');
  assert.ok(after.includes('# Generated by the first-run wizard'));
  assert.ok(after.includes('# trailing comment'));
  assert.ok(after.includes('READONLY_MODE=false'));
  assert.equal((after.match(/^ENTRY_ORDER=/gm) ?? []).length, 1, 'exactly one live key');
});

test('a missing key is appended', () => {
  const after = upsertEnvLine('TALLY_PORT=9000', 'ENTRY_ORDER', 'credit-first');
  assert.match(after, /^TALLY_PORT=9000$/m);
  assert.match(after, /^ENTRY_ORDER=credit-first$/m);
});

test('a COMMENTED-OUT key is documentation and is not hijacked', () => {
  // .env.example-style commentary must stay readable; writing into it would both corrupt the
  // comment and leave the real setting absent.
  const before = '# ENTRY_ORDER=debit-first   # pick one\nTALLY_PORT=9000';
  const after = upsertEnvLine(before, 'ENTRY_ORDER', 'credit-first');
  assert.ok(after.includes('# ENTRY_ORDER=debit-first   # pick one'), 'comment preserved verbatim');
  assert.match(after, /^ENTRY_ORDER=credit-first$/m, 'a live key was added');
});

test('writing to an empty file produces a usable one', () => {
  assert.match(upsertEnvLine('', 'ENTRY_ORDER', 'debit-first'), /^ENTRY_ORDER=debit-first$/m);
});

// --- per voucher type ---------------------------------------------------------------------------
// One global answer is WRONG: an accountant expects a different side to lead on a receipt than on a
// payment. These tests pin the precedence chain, because getting it wrong means either nagging the
// user about types they already answered, or silently writing a type they never answered.

const cfg = (o: Partial<EntryOrderConfig>): EntryOrderConfig => ({ default: null, byVoucherType: {}, ...o });

test('a type-specific answer beats the blanket default', () => {
  const r = resolveEntryOrderFor('Payment', cfg({ default: 'credit-first', byVoucherType: { Payment: 'debit-first' } }), undefined);
  assert.deepEqual(r, { order: 'debit-first', configured: true, source: 'voucher-type' });
});

test('types differ independently — answering Receipt says nothing about Payment', () => {
  const c = cfg({ byVoucherType: { Receipt: 'credit-first' } });
  assert.equal(resolveEntryOrderFor('Receipt', c, undefined).configured, true);
  // The whole point: Payment must still be ASKED, not inherited from Receipt.
  assert.equal(resolveEntryOrderFor('Payment', c, undefined).configured, false);
});

test('voucher types match case-insensitively', () => {
  // Tally calls it "Sales"; a user who answered for "sales" must not be asked twice.
  const c = cfg({ byVoucherType: { sales: 'credit-first' } });
  assert.equal(resolveEntryOrderFor('SALES', c, undefined).source, 'voucher-type');
  assert.equal(resolveEntryOrderFor('  Sales ', c, undefined).source, 'voucher-type');
});

test('the blanket default covers types with no answer of their own', () => {
  const r = resolveEntryOrderFor('RM Purchase', cfg({ default: 'debit-first' }), undefined);
  assert.deepEqual(r, { order: 'debit-first', configured: true, source: 'default' });
});

test('ENTRY_ORDER in .env is the last resort, below both', () => {
  // Back-compat: installs configured before per-type support existed still carry this key, and an
  // operator can still set one by hand.
  const r = resolveEntryOrderFor('Journal', cfg({}), 'credit-first');
  assert.deepEqual(r, { order: 'credit-first', configured: true, source: 'env' });
  // ...but a per-type answer still wins over it.
  const r2 = resolveEntryOrderFor('Journal', cfg({ byVoucherType: { Journal: 'debit-first' } }), 'credit-first');
  assert.equal(r2.order, 'debit-first');
});

test('nothing configured anywhere means ASK, not a silent default', () => {
  const r = resolveEntryOrderFor('Receipt', cfg({}), undefined);
  assert.equal(r.configured, false);
  assert.equal(r.source, 'none');
});

test('a corrupt config file degrades to asking, never to a guess or a crash', () => {
  // This file is on a customer's disk and can be hand-edited, truncated by a bad shutdown, or
  // simply absent on first run. None of those may take voucher writing down, and none may be
  // silently read as an answer.
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'entry-order-'));
  const file = path.join(dir, 'cfg.json');

  fs.writeFileSync(file, '{ this is not json');
  assert.deepEqual(readEntryOrderConfig(file), { default: null, byVoucherType: {} }, 'unparseable');

  fs.writeFileSync(file, JSON.stringify({ default: 'sideways', byVoucherType: { Receipt: 'upside-down', Sales: 'debit-first' } }));
  const cleaned = readEntryOrderConfig(file);
  assert.equal(cleaned.default, null, 'a nonsense default is dropped, not honoured');
  assert.deepEqual(cleaned.byVoucherType, { Sales: 'debit-first' }, 'a nonsense per-type value is dropped; valid siblings survive');
  assert.equal(resolveEntryOrderFor('Receipt', cleaned, undefined).configured, false, 'so Receipt is ASKED');

  assert.deepEqual(readEntryOrderConfig(path.join(dir, 'absent.json')), { default: null, byVoucherType: {} });
  fs.rmSync(dir, { recursive: true, force: true });
});

test('recording an answer for one type leaves the others alone', () => {
  let c: EntryOrderConfig = { default: null, byVoucherType: { Receipt: 'credit-first' } };
  c = applyEntryOrderChoice(c, 'debit-first', 'Payment');
  assert.deepEqual(c.byVoucherType, { Receipt: 'credit-first', Payment: 'debit-first' });
  assert.equal(c.default, null);
});

test('re-answering a type CORRECTS it instead of leaving two cased variants', () => {
  let c: EntryOrderConfig = { default: null, byVoucherType: { sales: 'credit-first' } };
  c = applyEntryOrderChoice(c, 'debit-first', 'Sales');
  assert.equal(Object.keys(c.byVoucherType!).length, 1, 'one entry, not two');
  assert.equal(resolveEntryOrderFor('sales', c, undefined).order, 'debit-first');
});

test('omitting the voucher type sets the blanket default and preserves per-type answers', () => {
  let c: EntryOrderConfig = { default: null, byVoucherType: { Receipt: 'credit-first' } };
  c = applyEntryOrderChoice(c, 'debit-first');
  assert.equal(c.default, 'debit-first');
  assert.deepEqual(c.byVoucherType, { Receipt: 'credit-first' }, 'a deliberate per-type answer is not erased by a later blanket one');
  assert.equal(resolveEntryOrderFor('Receipt', c, undefined).order, 'credit-first');
});
